config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.save
    redirect_to recipe_path(@recipe)
  end

  def edit
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :origin, :category, :cooked, :note, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>CuisineIndex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.input :name, label: 'Nom' %>
  <%= f.input :origin, label: 'Origine' %>
  <%= f.input :category, label: 'Catégorie' %>
  <%= f.input :cooked, label: 'Cuisiné',  as: :boolean, checked_value: true, unchecked_value: false %>
  <%= f.input :note, label: 'Note', collection: 1..3, as: :radio_buttons %>
  <%= f.input :comment, label: 'Commentaire' %>
  <%= f.button :submit, "Créer la recette", class: 'btn btn-primary' %>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<div class="row">
  <h1>Les recettes de Cath</h1>
</div>
<div class="row">
  <%= link_to "Ajouter une recette", new_recipe_path, class: "btn btn-primary" %>
</div>
<div class="row">
  <input class="form-control form-control-lg" type="text" placeholder="Rechercher une recette">
</div>
<% @recipes.each do |recipe| %>
  <div class="row recipe">
    <div class="recipe-title"><h2><%= link_to recipe.name, recipe_path(recipe) %></h2></div>
    <div class="recipe-info">
      <p>Source : <%= recipe.origin %>, Catégorie : <%= recipe.category %>
      <% if recipe.cooked %>
        , Testé et noté <%= recipe.note %>/3
      <% end %>
      </p>
    </div>
    <div class="recipe-actions">
      <%= link_to "Supprimer", recipe_path(recipe),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<div>
  <h1>Nouvelle recette</h1>
</div>
<div>
  <!-- <%= render 'form', recipe: @recipe %> -->
  <%= simple_form_for(@recipe) do |f| %>
  <%= f.input :name, label: 'Nom' %>
  <%= f.input :origin, label: 'Origine', collection: ['Livre', 'Dossier'], as: :radio_buttons %>
  <%= f.input :category, label: 'Catégorie' %>
  <%= f.input :cooked, label: 'Cuisiné',  as: :boolean, checked_value: true, unchecked_value: false %>
  <%= f.input :note, label: 'Note', collection: 1..3, as: :radio_buttons %>
  <%= f.input :comment, label: 'Commentaire' %>
  <%= f.button :submit, "Créer la recette", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>
<p><%= @recipe.origin %></p>
<p><%= @recipe.category %></p>
<p>Cuisiné: <%=@recipe.cooked %></p>
<p>Note: <%=@recipe.note %></p>
<p>Commentaires: <%=@recipe.comment %></p>
<%= link_to "Edit", edit_recipe_path(@recipe),
      method: :edit %>
<%= link_to "Delete", recipe_path(@recipe),
      method: :delete,
      data: { confirm: "Are you sure?" } %>